routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\backend\AdminDebtorController;
use App\Http\Controllers\backend\AdminDashboardController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');
});

Auth::routes();

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['auth', 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
    ],
    function () {
        Route::get('/dashboard', [DashboardController::class, 'index']);
        Route::get('/dashboard/{slug}', [DashboardController::class, 'show']);
    }
);

Route::prefix('/admin')->middleware('auth')->group(function () {
    Route::resource('/debtor', AdminDebtorController::class);
    Route::get('/', [AdminDashboardController::class, 'index']);
    Route::resource('/role', RoleController::class);
    Route::resource('/permission', PermissionController::class);
});

app/Models/Debtor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Debtor extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'slug',
        'stages',
        'summa_dolgi',
        'summa_dolgi_peni',
        'summa_priznano',
        'summa_priznano_peni',
        'summa_vziskano',
        'summa_vziskano_peni',
        'summa_other'
    ];
}

app/Http/Controllers/DebtorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Debtor;
use Illuminate\Http\Request;

class DebtorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Debtor  $debtor
     * @return \Illuminate\Http\Response
     */
    public function show(Debtor $debtor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Debtor  $debtor
     * @return \Illuminate\Http\Response
     */
    public function edit(Debtor $debtor)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Debtor  $debtor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Debtor $debtor)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Debtor  $debtor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Debtor $debtor)
    {
        //
    }
}

app/Http/Controllers/backend/AdminDashboardController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Debtor;

class AdminDashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $latest = Debtor::orderByDesc('created_at')->get();
        $updated = Debtor::orderByDesc('updated_at')->get();
        return view('backend.layouts.index', [
            'latest' => $latest,
            'updated' => $updated
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/backend/AdminDebtorController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Models\Debtor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AdminDebtorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Debtor::all();
        return view('backend.debtor.index', [
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.debtor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required'
        ]);

        $data = new Debtor([
            'name' => $request->input('name'),
            'slug' => Str::slug($request->input('name')),
            'stages' => $request->input('stages'),
            'summa_dolgi' => $request->input('summa_dolgi'),
            'summa_dolgi_peni' => $request->input('summa_dolgi_peni'),
            'summa_priznano' => $request->input('summa_priznano'),
            'summa_priznano_peni' => $request->input('summa_priznano_peni'),
            'summa_vziskano' => $request->input('summa_vziskano'),
            'summa_vziskano_peni' => $request->input('summa_vziskano_peni'),
            'summa_other' => $request->input('summa_other')
        ]);

        $data->save();
        return redirect('admin/debtor');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $data = DB::table('debtors')->where('slug', $slug)->first();
        return view('backend.debtor.show', [
            'data' => $data
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Debtor $debtor)
    {
        return view('backend.debtor.edit', compact('debtor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Debtor $debtor)
    {
        $request->validate([
            'name' => 'required'
        ]);

        $debtor->update($request->all());

        return redirect('admin/debtor');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Debtor $debtor)
    {
        $debtor->delete();

        return redirect()->route('debtor.index');
    }
}

resources/views/backend/debtor/create.blade.php
@extends('backend.layouts.head')

@section('content')

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    @include('backend.layouts.menu_item')
</nav>

<div class="mt-5">
    <h1>{{ __('lang.all_debtors') }}</h1>
    <hr>
    <p style="color: #ff0000;">* все поля должны быть заполнены!</p>
</div>


<div class="border p-3 bg-light">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <form method="post" action="{{ route('debtor.store') }}">
        @csrf

        <div class="mb-3">
            <label for="name" class="form-label font-weight-bold">Названия</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Имя должника">
        </div>

        <div class="mb-3">
            <label for="stages" class="form-label font-weight-bold">Процесс</label>
            <select name="stages" id="stages" class="custom-select">>
                <option selected value="0">Выберите процесс</option>
                <option disabled>1-этап</option>
                <option value="1">Изучение</option>
                <option value="2">Расчет суммы иска</option>
                <option disabled>2 этап</option>
                <option value="3">До судебное решение спора / Подготовка требования</option>
                <option value="4">До судебное решение спора / Отправка требования</option>
                <option value="5">До судебное решение спора / Переговоры с должником</option>
                <option disabled>3 этап</option>
                <option value="6">Решение спора судебным разбирательством / Подготовка иска</option>
                <option value="7">Решение спора судебным разбирательством / Отправка иска</option>
                <option value="8">Решение спора судебным разбирательством / Рассмотрение дела в суде</option>
                <option value="9">Решение спора судебным разбирательством / Получение решение и исполнительного листа</option>
                <option value="10">Решение спора судебным разбирательством / Признанная сумма судом</option>
                <option value="11">Решение спора судебным разбирательством / Отправка документов в БПИ</option>
                <option value="12">Решение спора судебным разбирательством / Исполнения решения суда</option>
                <option value="13">Сумма взысканной задолженности</option>
                <option value="14">Завершено</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="summa_dolgi" class="form-label font-weight-bold">Сумма долги</label><br>
            <input type="number" name="summa_dolgi" class="form-control" id="summa_dolgi" placeholder="Введите сумма">
        </div>

        <div class="mb-3">
            <label for="summa_dolgi_peni" class="form-label font-weight-bold">Сумма долги пени</label>
            <input type="number" name="summa_dolgi_peni" class="form-control" id="summa_dolgi_peni" placeholder="Введите сумма">
        </div>

        <button type="submit" class="btn btn-primary">Добавить</button>
        <button type="submit" class="btn btn-secondary" style="float: right;"><a onclick="javascript:history.back(); return false;">Назад</a></button>
    </form>
</div>


@endsection

resources/views/backend/debtor/edit.blade.php
@extends('backend.layouts.head')

@section('content')

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    @include('backend.layouts.menu_item')
</nav>

<div class="mt-5">
    <h1>{{ __('lang.all_debtors') }}</h1>
</div>


<div class="border p-3 bg-light">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div><br />
    @endif
    <form method="post" action="{{ route('debtor.update',$debtor->id) }}">
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="name" class="form-label font-weight-bold">Названия</label>
            <input type="text" name="name" class="form-control" value="{{$debtor->name}}">
        </div>
        <div class="mb-3">
            <label for="stages" class="form-label font-weight-bold">Процесс</label>
            <select name="stages" id="stages" class="custom-select">>
                <option selected value="0">Выберите процесс</option>
                <option disabled>1-этап</option>
                <option value="1" {{ old('stages', $debtor->stages) == 1 ? 'selected' : '' }}>Изучение</option>
                <option value="2" {{ old('stages', $debtor->stages) == 2 ? 'selected' : '' }}>Расчет суммы иска</option>
                <option disabled>2 этап</option>
                <option value="3" {{ old('stages', $debtor->stages) == 3 ? 'selected' : '' }}>До судебное решение спора / Подготовка требования</option>
                <option value="4" {{ old('stages', $debtor->stages) == 4 ? 'selected' : '' }}>До судебное решение спора / Отправка требования</option>
                <option value="5" {{ old('stages', $debtor->stages) == 5 ? 'selected' : '' }}>До судебное решение спора / Переговоры с должником</option>
                <option disabled>3 этап</option>
                <option value="6" {{ old('stages', $debtor->stages) == 6 ? 'selected' : '' }}>Решение спора судебным разбирательством / Подготовка иска</option>
                <option value="7" {{ old('stages', $debtor->stages) == 7 ? 'selected' : '' }}>Решение спора судебным разбирательством / Отправка иска</option>
                <option value="8" {{ old('stages', $debtor->stages) == 8 ? 'selected' : '' }}>Решение спора судебным разбирательством / Рассмотрение дела в суде</option>
                <option value="9" {{ old('stages', $debtor->stages) == 9 ? 'selected' : '' }}>Решение спора судебным разбирательством< / Получение решение и исполнительного листа/option>
                <option value="10" {{ old('stages', $debtor->stages) == 10 ? 'selected' : '' }}>Решение спора судебным разбирательством / Признанная сумма судом</option>
                <option value="11" {{ old('stages', $debtor->stages) == 11 ? 'selected' : '' }}>Решение спора судебным разбирательством / Отправка документов в БПИ</option>
                <option value="12" {{ old('stages', $debtor->stages) == 12 ? 'selected' : '' }}>Решение спора судебным разбирательством / Исполнения решения суда</option>
                <option value="13" {{ old('stages', $debtor->stages) == 13 ? 'selected' : '' }}>Сумма взысканной задолженности</option>
                <option value="14" {{ old('stages', $debtor->stages) == 14 ? 'selected' : '' }}>Завершено</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="summa_dolgi" class="form-label font-weight-bold">Сумма долги</label><br>
            <input type="text" name="summa_dolgi" class="form-control" value="{{$debtor->summa_dolgi}}">
        </div>

        <div class="mb-3">
            <label for="summa_dolgi_peni" class="form-label font-weight-bold">Сумма долги пени</label>
            <input type="text" name="summa_dolgi_peni" class="form-control" value="{{$debtor->summa_dolgi_peni}}">
        </div>

        <div class="mb-3">
            <label for="summa_priznano" class="form-label font-weight-bold">Сумма признано судом</label>
            <input type="text" name="summa_priznano" class="form-control" value="{{$debtor->summa_priznano}}">
        </div>

        <div class="mb-3">
            <label for="summa_priznano_peni" class="form-label font-weight-bold">Признано судом пени</label>
            <input type="text" name="summa_priznano_peni" class="form-control" value="{{$debtor->summa_priznano_peni}}">
        </div>

        <div class="mb-3">
            <label for="summa_vziskano" class="form-label font-weight-bold">Сумма взысканной задолженности</label>
            <input type="text" name="summa_vziskano" class="form-control" value="{{$debtor->summa_vziskano}}">
        </div>

        <div class="mb-3">
            <label for="summa_vziskano_peni" class="form-label font-weight-bold">Сумма взысканной задолженности По пени</label>
            <input type="text" name="summa_vziskano_peni" class="form-control" value="{{$debtor->summa_vziskano_peni}}">
        </div>

        <div class="mb-3">
            <label for="summa_other" class="form-label font-weight-bold">Взыскание других судебных расходов</label>
            <input type="text" name="summa_other" class="form-control" value="{{$debtor->summa_other}}">
        </div>

        <button type="submit" class="btn btn-primary">Обновить</button>
        <button type="submit" class="btn btn-secondary" style="float: right;"><a onclick="javascript:history.back(); return false;">Назад</a></button>
    </form>
</div>


@endsection

resources/views/backend/debtor/index.blade.php
@extends('backend.layouts.head')

@section('content')


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    @include('backend.layouts.menu_item')
    <ul class="nav navbar-nav ml-auto">
        <a href="debtor/create">
            <li class="btn btn-secondary " style="float: right;"> Добавить </li>
        </a>
    </ul>
</nav>

<div class="mt-5">
    <h1>{{ __('lang.all_debtors') }}</h1>
</div>
<div class="mb-2">
    <input class="form-control" type="text" id="myInput" onkeyup="myFunction()" placeholder="Названия">
</div>

<table class="table table-striped" id="myTable">
    <thead>
        <tr class="bg-warning">
            <th scope="col">#</th>
            <th scope="col">{{ __('lang.naimenovaniye_doljnika')}}</th>
            <th scope="col" style="text-align: center;">{{ __('lang.all_sum')}}</th>
            <th scope="col" style="text-align: center;">Действия</th>
        </tr>
    </thead>
    <tbody>
        @php $i = 1; @endphp
        @foreach ($data as $item)
        <tr>
            <th scope="row">{{$i++}}</th>
            <td>{{ $item->name }}</td>
            <td style="text-align: center;">{{ $item->summa_dolgi }}</td>
            <td style="text-align: center;">
                <a href="{{ route('debtor.edit',$item->id) }}">
                    <btn class="btn-sm btn-secondary">Изменить</btn>
                </a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

<script>
    function myFunction() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>

@endsection

resources/views/backend/debtor/show.blade.php
@extends('backend.layouts.head')

@section('content')

<div id="content" class="p-4 p-md-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
                <i class="fa fa-bars"></i>
                <span class="sr-only">Toggle Menu</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

@endsection